# Generated by Django 6.1.1 on 2026-10-09 07:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='e.g. {"mon": ["08:00", "20:00"], "sun": null}')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('accuracy_rating', models.FloatField(default=0.0, help_text='Rolling mean of patient accuracy ratings, 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('in', 'In stock'), ('low', 'Low stock'), ('out', 'Out of stock')], default='in', max_length=3)),
                ('indicative_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalogue.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pharmacies.pharmacyprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='pharmacyprofile',
            index=models.Index(fields=['is_verified', 'district'], name='pharmacies__is_veri_22f893_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['medicine', 'availability'], name='pharmacies__medicin_b8c655_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['last_updated_at'], name='pharmacies__last_up_6140db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('pharmacy', 'medicine')},
        ),
    ]
