# Generated by Django 6.1.1 on 2026-10-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('atc_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('nmra_reg_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('cream', 'Cream / ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('max_retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='NMRA published MRP in LKR, where price-controlled', max_digits=10, null=True)),
                ('equivalence_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('strength_unit', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('iu', 'IU'), ('%', '%')], max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.activeingredient')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_ingredients', to='catalogue.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.ManyToManyField(related_name='medicines', through='catalogue.MedicineIngredient', to='catalogue.activeingredient'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['equivalence_key', 'is_active'], name='catalogue_m_equival_a13a3e_idx'),
        ),
    ]
